<?
if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) die();



$arComponentParameters = array(
	"GROUPS" => array(
		
	),
	"PARAMETERS" => array(
		"SWOISTWOSTROKE"  =>  Array(
			"PARENT" => "BASE",
			"NAME" => GetMessage("MYCODEPARTHNER_NAME.COMPONENTONE_PARAM_SWOISTWOSTROKE_NAME"),
			"TYPE" => "STRING",
		),
		"SPISOK"  =>  Array(
			"PARENT" => "BASE",
			"NAME" => GetMessage("MYCODEPARTHNER_NAME.COMPONENTONE_PARAM_SPISOK_NAME"),
			"TYPE" => "LIST",
			"VALUES" => ""
		),
		"TCHEKBOX"  =>  Array(
			"PARENT" => "BASE",
			"NAME" => GetMessage("MYCODEPARTHNER_NAME.COMPONENTONE_PARAM_TCHEKBOX_NAME"),
			"TYPE" => "CHECKBOX",
		),
		"FILEFORDOWNLOAD"  =>  Array(
			"PARENT" => "BASE",
			"NAME" => GetMessage("MYCODEPARTHNER_NAME.COMPONENTONE_PARAM_FILEFORDOWNLOAD_NAME"),
			"TYPE" => "FILE",
		),
		"NASTROIKIAHAX"  =>  Array(
			"PARENT" => "AJAX_SETTINGS",
			"NAME" => GetMessage("MYCODEPARTHNER_NAME.COMPONENTONE_PARAM_NASTROIKIAHAX_NAME"),
			"TYPE" => "STRING",
		),
		"SWOISTWOSTROKEDEFAULT"  =>  Array(
			"PARENT" => "BASE",
			"NAME" => GetMessage("MYCODEPARTHNER_NAME.COMPONENTONE_PARAM_SWOISTWOSTROKEDEFAULT_NAME"),
			"TYPE" => "STRING",
			'DEFAULT' => GetMessage("MYCODEPARTHNER_NAME.COMPONENTONE_PARAM_SWOISTWOSTROKEDEFAULT_DEFAULT"),
		),
		
	),
);
?>
